name: Angular CI/CD Pipeline with SonarQube Gate

on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ development ]

jobs:
  sonar-security:
    name: SonarQube Security Check
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: SonarQube Scan (CLI)
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=angular-scan \
            -Dsonar.host.url=http://localhost:9001 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate
        run: |
          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "http://localhost:9001/api/qualitygates/project_status?projectKey=angular-scan" \
            | jq -e '.projectStatus.status == "OK"'
